services:
  mysqldb:
    image: mysql:8.0.36-debian
    environment:
      MYSQL_DATABASE: user_service
      MYSQL_ROOT_PASSWORD: a123
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  mongodb:
    image: mongo:8.0.0-rc4-jammy
    environment:
      - MONGO_INITDB_DATABASE=appointment_service
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo_data:/data/db
volumes:
  mysqldb:
  mongodb: