# Generated by Django 4.1.13 on 2024-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.IntegerField()),
                ('ammount', models.IntegerField()),
                ('item', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('bill_date', models.DateField()),
                ('bill_details', models.CharField(max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
